"""Regenerate and check lute/jlpt_data/grammar/zh.json.

The 595 Chinese glosses in that file are hand-written for a Mandarin speaker
learning Japanese; this script is their source of truth, so that a gloss can be
corrected here and the data file re-derived rather than edited in place.  It is
also the check on that file:

  python -m scripts.generate_grammar_zh [--write]

Without --write it only reports: ids present in the n*.json files but missing a
gloss, glosses whose id no longer exists, and glosses outside 4~40 characters.

The JLPT grammar files themselves come from jkindrix/japanese-language-data
(CC BY-SA 4.0, see ATTRIBUTION.md) and are not generated here.
"""

import argparse
import json
import os
import sys

BASE = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "lute",
    "jlpt_data",
    "grammar",
)
LEVELS = ["n5", "n4", "n3", "n2", "n1"]

# id -> 简体中文释义（面向中文母语的日语学习者，4~24 汉字，用「……」表示后接内容）
ZH = {
    # ===== N5 =====
    "desu-polite-copula": "……是（礼貌断定，です）",
    "da-plain-copula": "……是（简体断定，だ）",
    "deshita-past-polite-copula": "……是（礼貌过去式）",
    "dewa-arimasen-negative-polite-copula": "……不是（礼貌否定）",
    "masu-polite-verb": "……（动词礼貌体ます）",
    "mashita-polite-past-verb": "……了（礼貌过去式）",
    "masen-polite-negative-verb": "不……（礼貌否定）",
    "masendeshita-polite-past-negative-verb": "没……（礼貌过去否定）",
    "particle-wa-topic": "表示主题（は，读wa）",
    "particle-ga-subject": "表示主语、新信息（が）",
    "particle-o-object": "表示宾语（を）",
    "particle-ni-target": "表示对象、时间、地点（に）",
    "particle-de-means": "表示手段、场所（で）",
    "particle-to-and-with": "和……；与……一起（と）",
    "particle-no-possession": "的；名词修饰（の）",
    "particle-e-direction": "表示方向（へ，读e）",
    "particle-kara-from": "从……（起点，から）",
    "particle-made-until": "到……为止（まで）",
    "particle-mo-also": "也；同样（も）",
    "particle-ka-question": "表示疑问（か）",
    "particle-ne-seeking-agreement": "吧？对吧？（ね）",
    "particle-yo-emphasis": "啊、哟（告知新信息，よ）",
    "kore-sore-are-demonstratives": "这／那／那远／哪（指示代词）",
    "kono-sono-ano-dono-attributive": "这个／那个……（连体指示）",
    "koko-soko-asoko-doko": "这里／那里／哪里（场所指示）",
    "arimasu-existence-inanimate": "有……（无生命物）",
    "imasu-existence-animate": "有……（人、动物）",
    "te-form-basic": "て形（连接、基础）",
    "te-kudasai-request": "请做……（てください）",
    "te-imasu-progressive": "正在……；处于……状态",
    "nai-form": "不……（简体否定）",
    "ta-form": "……了（简体过去）",
    "i-adjective-nonpast": "……的（い形容词非过去）",
    "i-adjective-negative": "不……（い形容词否定）",
    "i-adjective-past": "曾经……（い形容词过去）",
    "na-adjective-nonpast": "……的（な形容词非过去）",
    "na-adjective-attributive": "……的（な形容词连体）",
    "na-adjective-negative": "不……（な形容词否定）",
    "na-adjective-past": "曾经……（な形容词过去）",
    "mashou-volitional": "一起……吧（ましょう）",
    "mashou-ka-invitation": "要不要……？（邀请、提议）",
    "tai-desire": "想做……（たい）",
    "ga-hoshii-wanting-thing": "想要……（ほしい）",
    "hou-ga-comparative": "A比B更……（比较）",
    "ichiban-superlative": "最……（最高级）",
    "counter-tsu": "……个（つ通用量词）",
    "counter-people-nin": "……人（にん人数）",
    "question-words-basic": "何／谁／哪里／何时／怎么",
    "nai-de-kudasai": "请不要做……（ないでください）",
    "particle-ya-non-exhaustive": "……和……等（や，非穷尽）",
    "masenka-invitation": "要不要……？（ませんか）",
    "mou-ta-already": "已经……了（もう）",
    "mada-not-yet": "还没……；仍然（まだ）",
    "toki-ni-when-basic": "在……的时候（とき）",
    "issho-ni-together": "和……一起（一緒に）",
    "dake-only-basic": "只……；仅（だけ基础）",
    "i-adj-adverbial-ku": "……地（い形容词副词形）",
    "na-adj-adverbial-ni": "……地（な形容词副词形）",
    "i-adj-te-joining-kute": "……而且；因为（くて连接）",
    "na-adj-te-joining-de": "……而且；因为（で连接）",
    "mo-mo-both": "既……又……（も…も）",
    "to-exhaustive-listing": "……和……（と，穷尽列举）",
    "location-nouns-ue-shita": "在……上／下／前／后等",
    "ikutsu-how-many": "几个；几岁（いくつ）",
    "ikura-how-much": "多少钱；多少（いくら）",
    "nanji-what-time": "几点；什么时候（何時）",
    "nanyoubi-day-of-week": "星期几（何曜日）",
    "counter-ji-oclock": "……点（時钟点）",
    "counter-fun-minute": "……分（分钟）",
    "counter-sai-age": "……岁（歳年龄）",
    "counter-en-money": "……日元（円）",
    "counter-hon-long": "……根（本细长物）",
    "counter-mai-flat": "……张（枚薄片物）",
    "mai-every-prefix": "每……（毎前缀）",
    "jikan-time-duration": "……小时（時間时长）",
    "i-adj-desu-politeness": "……的（い形礼貌体）",
    "kara-cause": "因为……；由于（から）",
    "potential-form": "能……；会……（可能态）",
    # ===== N4 =====
    "passive-form": "被……；受到（被动，含受害）",
    "causative-form": "让……做；使（使役态）",
    "ta-koto-ga-aru": "曾经……过（经验）",
    "tsumori-intention": "打算……；计划（つもり）",
    "to-omou": "我觉得……；认为（と思う）",
    "to-iu": "叫做……；说……（と言う）",
    "darou-deshou-conjecture": "大概……吧；推测（でしょう）",
    "kamoshirenai-might": "也许……；可能（かもしれない）",
    "hazu-expected": "应该……；按理（はず）",
    "tara-conditional": "如果……；要是（たら条件）",
    "ba-conditional": "如果……（ば条件）",
    "to-conditional": "一……就……（と条件）",
    "nara-conditional": "如果……；至于（なら）",
    "volitional-form": "打算……吧（意志形）",
    "te-wa-ikenai-prohibition": "不许……；禁止（てはいけない）",
    "te-mo-ii-permission": "可以……（てもいい）",
    "nakereba-naranai": "必须……；不得不（なければならない）",
    "nakute-mo-ii": "不必……；可以不（なくてもいい）",
    "node-cause": "因为……；由于（ので，较柔和）",
    "ga-kedo-although": "但是……；虽然（が／けど）",
    "n-desu-explanation": "是……（说明、解释，んです）",
    "ni-naru-become": "变成……（になる）",
    "ni-suru-decide": "决定……；使成（にする）",
    "hajimeru-auxiliary": "开始……（始める）",
    "owaru-finish": "做完……（終わる）",
    "sugiru-too-much": "太……；过度（すぎる）",
    "yasui-easy": "容易……（やすい）",
    "nikui-hard": "难……；不易（にくい）",
    "noun-modifying-clause": "……的（名词修饰从句）",
    "tari-tari-suru": "又……又……（たりする）",
    "jidoushi-tadoushi": "自他动词对应（自动／他动）",
    "garu-third-person-emotion": "（他）显得……（がる）",
    "kata-way-of-doing": "……的方法（方）",
    "you-ni-suru": "设法做到……（ようにする）",
    "te-kara-after-doing": "……之后（てから）",
    "mae-ni-before-doing": "在……之前（前に）",
    "ato-de-after-doing": "……之后（後で）",
    "koto-ga-dekiru": "能够……（ことができる）",
    "koto-ni-suru-decide": "决定……（ことにする）",
    "koto-ni-naru-be-decided": "就决定……（ことになる）",
    "nasai-command": "做……（なさい，轻柔命令）",
    "te-hoshii-want-someone": "希望（别人）做……（てほしい）",
    "shi-reason-listing": "又……；而且（し，列举理由）",
    "you-to-omou-volitional-intent": "我想……；打算（意志形＋と思う）",
    "te-kureru-favor-received": "（别人）给我做……（てくれる）",
    "te-morau-request-favor": "请（别人）做……（てもらう）",
    "te-ageru-favor-given": "（我）给（别人）做……（てあげる）",
    "ageru-give-outward": "给……（向外，あげる）",
    "kureru-give-toward": "（别人）给我（くれる）",
    "morau-receive": "收到……；得到（もらう）",
    "o-v-kudasai-polite-honor": "请……（お～ください，尊敬）",
    "sonkeigo-reru-rareru": "（尊敬）做……（被动敬语）",
    "humble-o-suru": "（谦让）我做……（お～する）",
    "sou-iu-kou-iu": "这种／那种……（こういう等）",
    "tai-to-omou-want-to-think": "我想做……（たいと思う）",
    "ba-ai-in-case": "在……情况下；如果（場合）",
    "zutsu-each-per": "每……；各（ずつ）",
    "tsumori-datta-had-intended": "原本打算……（つもりだった）",
    "hazu-datta-was-supposed": "本应……；应该已经（はずだった）",
    "demo-noun-even": "即使……；之类（でも）",
    "te-itadaku-polite-favor-received": "（谦让）承蒙（别人）做（いただく）",
    "ba-ii-should": "只要……就行（ばいい）",
    "yaru-casual-giving": "给……（随意，やる）",
    "v-temo-even-if": "即使……也（ても）",
    "irassharu-honorific": "（尊敬）去／来／在（いらっしゃる）",
    "ossharu-honorific": "（尊敬）说（おっしゃる）",
    "goran-ni-naru-honorific": "（尊敬）看（ご覧になる）",
    "nasaru-honorific": "（尊敬）做（なさる）",
    "mairu-humble": "（谦让）去／来（参る）",
    "mousu-humble": "（谦让）说；叫（申す）",
    "itadaku-humble-verb": "（谦让）领受／吃（いただく）",
    "kudasaru-honorific-verb": "（尊敬）给我（くださる）",
    "shika-nai": "只……；仅有（しか，否定）",
    "ga-suki-kirai": "喜欢……／讨厌……（が好き等）",
    "ga-wakaru": "懂……；明白（がわかる）",
    "ga-dekiru": "会……；能做（ができる）",
    "ga-kikoeru-mieru": "听得见／看得见（が聞こえる等）",
    "dakara-so": "所以……；因此（だから）",
    "sorede-and-then": "于是……；然后（それで）",
    "sorekara-after": "然后……；此外（それから）",
    "shikashi-but": "但是……；然而（しかし）",
    "kedomo-formal-but": "但是……；不过（けれども）",
    "toka-listing": "……之类的（とか，随意列举）",
    "tte-quotation": "（口语）说……；所谓的（って）",
    "soredemo-even-so": "即便如此……（それでも）",
    "sou-da-appearance": "看起来……；似乎（そうだ样态）",
    "sou-da-hearsay": "听说……；据说（そうだ传闻）",
    "you-ka-to-omou": "想要……（正考虑，かと思う）",
    "you-da-appearance": "似乎……；好像（ようだ，有根据）",
    "mitai-looks-like": "好像……；像（みたい，口语）",
    # ===== N3 =====
    "rashii-seems": "好像……；有……特征（らしい）",
    "te-oku": "预先做……；保持状态（ておく）",
    "te-shimau": "做完；不小心做（てしまう）",
    "te-aru": "已（被人）做好……（てある）",
    "te-miru": "试着做……（てみる）",
    "te-iku": "……下去；去（ていく）",
    "te-kuru": "……过来；逐渐（てくる）",
    "nagara": "一边……一边（ながら）",
    "uchi-ni": "趁……；在……期间（うちに）",
    "aida-ni": "在……期间；当中（間に）",
    "ta-bakari": "刚……（たばかり）",
    "ta-tokoro": "刚……；正要……（ところ）",
    "tame-ni": "为了……；因为（ために）",
    "you-ni-purpose": "为了……；以便（ように）",
    "noni-although": "虽然……却（のに）",
    "okage-sei-de": "多亏……；都怪（おかげ／せいで）",
    "bakari-only": "只……；净是（ばかり）",
    "kakeru-halfway": "做一半；刚要（かける）",
    "hodo-extent": "到……程度；不如（ほど）",
    "kurai-extent": "大约……；程度（くらい）",
    "koto-nominalizer": "……这件事（こと名词化）",
    "no-nominalizer": "……这件事（の名词化）",
    "tabi-ni-every-time": "每次……；每当（たびに）",
    "ka-dou-ka": "是否……（かどうか）",
    "ni-tsuite": "关于……；就（について）",
    "ni-totte": "对……来说；从……角度（にとって）",
    "ni-yotte": "由……；根据；被（によって）",
    "beki-da": "应该……；应当（べきだ）",
    "ta-hou-ga-ii": "最好……；还是……好（たほうがいい）",
    "nakucha-nakya": "必须……（なくちゃ等，口语）",
    "ba-yokatta": "当初要是……就好了（ばよかった）",
    "ba-hodo": "越……越……（ば～ほど）",
    "causative-passive": "被迫……；被使役（使役被动）",
    "mama": "就那样……；原封不动（まま）",
    "zu-ni": "没……就（ずに）",
    "tagaru-third-person-desire": "（他）想要……（たがる）",
    "sae-even": "连……都（さえ，强调）",
    "koso-precisely": "正是……；唯有（こそ）",
    "to-tan-moment": "刚一……就（とたんに）",
    "shidai-depending": "视……而定；一……就（次第）",
    "kagiri-as-long-as": "只要……；在……范围内（限り）",
    "darake-full-of": "满是……；净是（だらけ，贬义）",
    "furi-wo-suru-pretend": "假装……；装作（ふりをする）",
    "kuse-ni-despite": "明明……却（くせに，责难）",
    "wake-da-meaning": "就是说……；难怪（わけだ）",
    "wake-dewa-nai": "并非……；并不是（わけではない）",
    "you-ga-nai-no-way": "无法……；毫无办法（ようがない）",
    "pponashi-left": "一直……；放着（っぱなし）",
    "ni-shitemo-even": "即使……；就算（にしても）",
    "to-wa-kagiranai": "未必……；不一定（とは限らない）",
    "nai-koto-wa-nai": "并非不……；有可能（ことはない）",
    "irai-since": "自……以来（以来）",
    "ni-taishite-toward": "对……；与……相反（に対して）",
    "ni-kanshite-regarding": "关于……；有关（に関して）",
    "ni-kawatte-instead": "代替……；代表（にかわって）",
    "toshite-as": "作为……；以……身份（として）",
    "ni-oite-in-at": "在……；关于（において）",
    "muke-targeted-for": "面向……；以……为对象（向け）",
    "muki-suitable-for": "适合……；合乎（向き）",
    "ni-tsurete-as": "随着……（につれて）",
    "to-tomoni-together": "与……同时；连同（とともに）",
    "kiri-only": "只……；仅（きり）",
    "ta-kiri-since-last": "自……后（再没）……（たきり）",
    "dake-ni-precisely": "正因为……；毕竟（だけに）",
    "dake-atte-as-expected": "不愧是……；毕竟（だけあって）",
    "bakari-ni-merely": "只因……（ばかりに，常含负面）",
    "bakari-ka-not-only": "不仅……而且（ばかりか）",
    "to-iu-yori-rather": "与其说……不如（というより）",
    "to-ieba-speaking-of": "说起……；谈到（と言えば）",
    "to-itte-mo-although": "虽说是……（と言っても）",
    "to-itta-such-as": "诸如……；像（といった）",
    "ppoi-seems": "像是……；有点（っぽい）",
    "ge-looking": "显得……；带……样子（げ）",
    "dokoro-ka-far-from": "别说……；岂止（どころか）",
    "dokoro-dewa-nai-no-time": "哪有空……；谈何（どころではない）",
    "ippou-de-one-hand": "另一方面……；同时（一方で）",
    "ippou-da-keeps": "一味……；不断（一方だ）",
    "ue-de-upon": "在……基础上；先（上で）",
    "warini-considering": "虽……却；比较起来（わりに）",
    "te-tamaranai-unbearably": "……得不得了；忍不住（たまらない）",
    "te-naranai-cant-help": "不禁……；忍不住（ならない）",
    "chuu-during": "在……中；整个（中）",
    "gimi-tendency": "有点……倾向（気味）",
    "tsuzukeru-continue": "继续……；一直（続ける）",
    "naoshi-redo": "重做……；重新（直す）",
    "au-together": "互相……；一起（合う）",
    "dashi-suddenly-start": "突然开始……（出す）",
    "komi-into": "充分……；进入（込む）",
    "saichu-in-the-middle": "正在……当中（最中）",
    "kke-casual-wondering": "……来着？（っけ，口语）",
    "mono-reason-assertion": "因为……嘛（もの，辩解）",
    "mon-casual-because": "因为……啊（んだもん，口语）",
    "nai-de-without-doing": "没……就（ないで）",
    "ni-chigainai-must": "一定……；肯定（に違いない）",
    "koto-da-emphatic": "应该……；重要的是（ことだ）",
    "hoka-nai-no-choice": "只好……；只能（ほかない）",
    "koto-ni-surprise": "令人……的是（ことに）",
    "kurai-nara-rather": "与其……不如（くらいなら）",
    "ni-kakete-through": "从……到……（にかけて）",
    "igai-other-than": "除……之外；别的（以外）",
    "okini-intervals": "每隔……（おきに）",
    "gotoni-each": "每……；各自（ごとに）",
    "kawari-ni-instead": "代替……；作为交换（代わりに）",
    "n-da-kara-emphatic": "因为……嘛（んだから）",
    "wake-ga-nai": "不可能……；怎么会（わけがない）",
    "shou-ga-nai": "没办法；只好如此（しょうがない）",
    "te-shou-ga-nai": "……得不得了（しょうがない）",
    "te-shikata-ga-nai": "……得没办法（しかたがない）",
    "kko-nai": "绝不可能……；没门（っこない）",
    "nan-te-how": "竟然……；什么的（なんて）",
    "nan-ka-dismissive": "之类的；什么的（なんか，轻视）",
    "buri-ni-first-time": "时隔……（ぶりに）",
    "nai-wake-ni-ikanai": "不能不做……；不得不（わけにはいかない）",
    "wake-ni-wa-ikanai": "不能……；不便（わけにはいかない）",
    "tsuide-ni": "顺便……；趁便（ついでに）",
    "wo-hajime-including": "以……为首；包括（をはじめ）",
    "te-koso-only-by": "正因为……才（てこそ）",
    "bakari-de-naku": "不仅……而且（ばかりでなく）",
    "dake-de-naku": "不仅……而且（だけでなく）",
    "ni-kimatte-iru": "一定……；毫无疑问（に決まっている）",
    "zuni-sumu": "用不着……；免得（ずに済む）",
    "ni-kurabete-compared": "与……相比（に比べて）",
    "te-hajimete-only-after": "只有……之后才（て初めて）",
    "ni-ataru-correspond": "相当于……；正值（に当たる）",
    "tatoe-temo": "即使……（たとえ～ても）",
    "te-goran-try-casual": "试试看……（てごらん）",
    "mono-da-general": "本来就是……；应该（ものだ）",
    "ki-ga-suru-feel-like": "觉得……；感觉（気がする）",
    "ni-atatte-occasion": "在……之际；当（にあたって，郑重）",
    "ni-sakidatte-prior": "在……之前；先于（に先立って）",
    "wo-kikkake-ni": "以……为契机；趁（をきっかけに）",
    # ===== N2 =====
    "wo-keiki-ni": "以……为转机；借（を契機に）",
    "ni-tsuki-due-to": "由于……；每（につき）",
    "yue-ni-because": "因为……；所以（ゆえに，书面）",
    "koto-kara-from-fact": "从……可知；基于（ことから）",
    "amari-too-much": "过于……；因太（あまり）",
    "ba-koso-precisely-because": "正因为……（ばこそ）",
    "kara-koso-precisely-because": "正因为……（からこそ）",
    "ni-tomonatte-accompany": "伴随……；随着（に伴って）",
    "ni-oujite-depending": "根据……；响应（に応じて）",
    "ni-kotaete-response": "响应……；回应（にこたえて）",
    "ni-kakawarazu-regardless": "不论……；不管（にかかわらず）",
    "ni-mo-kakawarazu-despite": "尽管……却（にもかかわらず）",
    "wo-towazu-regardless": "不论……；不问（を問わず）",
    "wa-tomokaku": "……姑且不论（はともかく）",
    "wa-sate-oki": "……暂且不说（はさておき）",
    "ni-kagitte-only": "偏偏……；唯独（に限って）",
    "ni-kagirazu-not-only": "不仅……；不限于（に限らず）",
    "zu-ni-wa-irarenai": "忍不住……；不禁（ずにはいられない）",
    "nai-dewa-irarenai": "忍不住……；不禁（ではいられない）",
    "te-wa-irarenai": "不能一直……；待不下去（てはいられない）",
    "ni-shiro-ni-seyo": "即使……；无论（にしろ／にせよ）",
    "toshite-mo-even-as": "即使作为……；即便（としても）",
    "you-to-regardless": "无论……；不管（ようと）",
    "you-to-mai-to": "做不做……；无论（ようとまいと）",
    "mai-not-likely": "不（会）……；不会吧（まい）",
    "nuku-fully-do": "做到底……；彻底（抜く）",
    "kane-nai-might": "有可能……；说不定（かねない）",
    "kane-ru-hard-to": "难以……；不便（かねる）",
    "dzurai-hard-emotional": "难……；不好开口（づらい）",
    "gatai-difficult": "难以……（がたい，郑重）",
    "beku-in-order-to": "为了……；以期（べく，书面）",
    "wa-mochiron": "……自不待言；当然（はもちろん）",
    "wo-tsuujite-through": "通过……；整个（を通じて）",
    "ni-wataru-span": "长达……；横跨（にわたって）",
    "wo-chuushin-ni-centered": "以……为中心；围绕（を中心に）",
    "wo-komete": "饱含……；带着（を込めて）",
    "ni-shite-wa": "就……而言；作为（にしては）",
    "ni-shite": "在……之时；身为（にして）",
    "sue-ni-after": "经过……之后；终（末に）",
    "dake-no-koto-wa-aru": "不愧是……；名副其实（だけのことはある）",
    "made-mo-nai": "用不着……；不必（までもない）",
    "to-iu-mono-da": "这就是……；所谓（というものだ）",
    "to-iu-mono-dewa-nai": "并非只是……；不是（というものではない）",
    "mono-dakara": "因为……嘛（ものだから）",
    "yara-yara": "……啦……啦（やら，乱）",
    "kara-shite": "从……来看；从（からして）",
    "kara-suru-to": "从……看来；按（からすると）",
    "kara-ni-wa": "既然……就（からには）",
    "no-minarazu": "不仅……而且（のみならず）",
    "to-wa-ie": "虽说……；不过（とはいえ）",
    "to-wa-iu-mono-no": "虽说如此……（とはいうものの）",
    "ni-shite-mireba": "从……来看；就（にしてみれば）",
    "kara-to-itte": "并不能因为……就（からといって）",
    "koto-dakara": "既然是……（ことだから）",
    "te-kara-to-iu-mono": "自从……以来（てからというもの）",
    "tsutsu-aru": "正在……；逐渐（つつある）",
    "dake-mashi-da": "至少……；还算好（だけましだ）",
    "ya-inaya": "一……就……（や否や，书面）",
    "ka-nai-ka-no-uchi-ni": "刚……就……（か～ないかのうちに）",
    "sobakara": "刚……就（又）……（そばから）",
    "ja-arumai-shi": "又不是……；既然不是（じゃあるまいし）",
    "to-bakari-ni": "仿佛在说……；像（とばかりに）",
    "to-areba": "若是……；既然是（とあれば）",
    "nai-made-mo": "即使不算……也（までも）",
    "no-moto-de": "在……之下；基于（のもとで）",
    "sou-ni-nai": "看不出……；没迹象（そうにない）",
    "zu-jimai": "最终没……；落得（ずじまい）",
    "ta-tokoro-de": "即使……也白费（たところで）",
    "nani-shiro": "总之……；毕竟（なにしろ）",
    "nani-se": "总之……；说到底（なにせ）",
    "ageku-ni-end-up": "结果……；到头来（あげく，负面）",
    "hanmen-on-other-hand": "另一方面……；相反（反面）",
    "kara-miru-to": "从……来看；据（から見ると）",
    "to-iu-koto-da": "也就是说……；听说（ということだ）",
    "kekka-result": "结果……；由于（結果）",
    "shidai-de": "视……而定；根据（次第で）",
    "ni-itaru": "达到……；以至（に至る）",
    "ni-itaru-made": "直到……；甚至（に至るまで）",
    "sai-ni": "在……时；当（際に，郑重）",
    "wo-hete": "经由……；经过（を経て）",
    "wo-fumaete": "基于……；根据（を踏まえて）",
    "wo-yoso-ni": "不顾……；无视（をよそに）",
    "doori-just-as": "正如……；按照（通り）",
    "ikan-depending": "视……而定；依（いかん，郑重）",
    "uru-possible": "可能……；能够（得る）",
    "to-atte": "正因为……；由于（とあって）",
    "te-kara-denai-to": "除非先……否则（てからでないと）",
    "nai-koto-niwa": "不……就不能（ことには）",
    "to-mieru": "看来……；似乎（とみえる）",
    "to-sureba": "如果……；假设（とすれば）",
    "wa-oroka": "连……都不；何况（はおろか）",
    "ni-suginai": "只不过是……；仅仅（にすぎない）",
    "tatte-even-casual": "即使……（たって，口语）",
    "koto-tote": "因为……；由于（こととて，郑重）",
    "atte-no-thanks-to": "多亏……才；因有（あっての）",
    "ni-terashite": "依照……；对照（に照らして）",
    "kagiri-da-emotional": "极其……；……至极（限りだ）",
    "kiwamari-nai": "极其……；无比（極まりない）",
    "hodo-no-mono-dewa-nai": "没那么严重；不至于（ほどのことではない）",
    "zutomo-even-without": "即使不……也（ずとも）",
    "dano-dano": "……啦……啦（だの，贬义列举）",
    "to-miru-see-as": "视为……；看作（とみる）",
    "you-de-seemingly": "看似……实则（ようで）",
    "sae-sureba-if-only": "只要……就（さえ～ば）",
    "datte-casual-because": "因为……嘛（だって，口语）",
    "to-itte-without-particular": "没什么特别……（といって）",
    "you-nara-if-looks": "如果看来……（ようなら）",
    "you-dewa-if-its": "照这样下去……（ようでは）",
    "zukume-nothing-but": "全是……；净是（ずくめ）",
    "mamire-smeared": "沾满……；满是（まみれ）",
    "buru-pretend": "装作……；摆出（ぶる）",
    "meku-have-look": "带有……气息；似（めく）",
    "mono-ga-aru": "颇有……；有……之处（ものがある）",
    "to-iu-ka": "或者说……；准确说（というか）",
    "to-mo-naku": "无意中……；不自觉地（ともなく）",
    "kara-iu-to": "从……来说；依（からいうと）",
    "naku-mo-nai": "并非不……；也不是（なくもない）",
    "ni-kakatte-iru": "取决于……；关乎（にかかっている）",
    "to-iu-no-wa": "所谓……；之所以（というのは）",
    "hate-ni-after": "最终……；到头来（果てに）",
    "sobireru-miss-chance": "错过……；没来得及（そびれる）",
    "yashinai-emphatic": "根本不……；绝不（やしない）",
    "makuru-extensively": "大干……；猛做（まくる）",
    "to-iu-koto-wa": "也就是说……；那么（ということは）",
    "ka-to-iu-to": "至于是否……（かというと）",
    "mono-to-shite": "作为……；视为（ものとして）",
    "te-mo-ii-kurai": "甚至到了……地步（てもいいくらい）",
    "ato-wa-rest": "剩下的……；此后（あとは）",
    "dake-nara": "如果只是……；仅（だけなら）",
    "nai-nomi-narazu": "不仅不……（ないのみならず）",
    "tsutsu-while": "一边……；虽然（つつ）",
    "ni-shitagatte": "随着……；依照（にしたがって）",
    "ni-sotte-along": "沿着……；按照（に沿って）",
    "mono-no-although": "虽然……；尽管（ものの）",
    "ka-no-you-ni": "宛如……；好像（かのように）",
    "mono-nara-if-possible": "如果能……；要是（ものなら）",
    "wo-motoni-based-on": "以……为基础；基于（をもとに）",
    "ue-ni-in-addition": "而且……；加上（上に）",
    "ue-wa-now": "既然……就（上は）",
    "ijou-since": "既然……；只要（以上）",
    "shikamo-moreover": "而且……；加之（しかも）",
    "bakari-no": "只有……；一味（ばかりの）",
    "osore-ga-aru": "有……之虞；恐怕（恐れがある）",
    "zaru-wo-enai": "不得不……；被迫（ざるを得ない）",
    "ka-to-omou-to": "刚一……就（かと思うと）",
    "hodo-dewa-nai": "没到……程度；并非（ほどではない）",
    "ni-kataku-nai": "不难……；容易（に難くない）",
    "wo-yogi-naku-sareru": "被迫……；不得不（を余儀なくされる）",
    "wo-kinjienai": "不禁……；难以抑制（を禁じ得ない）",
    # ===== N1 =====
    "zu-ni-wa-okanai": "必定会……；难免（ずにはおかない）",
    "nai-dewa-okanai": "必定……；势必要（ではおかない）",
    "ni-mo-mashite": "更……；何况（にもまして）",
    "wo-mono-to-mo-sezu": "不畏……；不管（をものともせず）",
    "ikan-ni-yorazu": "不论……；不管（いかんによらず）",
    "tomo-arou": "身为……；堂堂（ともあろう）",
    "narade-wa-no": "唯有……才；特有（ならでは）",
    "ni-atte": "在……之际；处于（にあって）",
    "taru-mono-as-x": "作为……者应（たる者）",
    "nari-nari": "……也好……也好；或（なり～なり）",
    "to-iwazu-to-iwazu": "无论……还是（といわず～といわず）",
    "de-are-de-are": "无论……还是（であれ～であれ）",
    "made-da": "大不了……；只是（までだ）",
    "made-no-koto-da": "不过是……；只是（までのことだ）",
    "to-wa": "竟然……；所谓（とは）",
    "ni-itatte-wa": "至于……；说起（に至っては）",
    "wo-oite": "除……之外；唯有（をおいて）",
    "koto-nashi-ni": "不……就；未（ことなしに）",
    "kitte-no": "首屈一指的……；最（きっての）",
    "tomo-nareba": "一旦成为……；当（ともなれば）",
    "no-itari": "……之至；极其（の至り）",
    "katawara": "一边……一边；同时（かたわら）",
    "gatera-while": "顺便……；在……同时（がてら）",
    "bekarazu": "不可……；不该（べからず）",
    "zu-ni-wa-sumanai": "不得不……；躲不过（ずにはすまない）",
    "to-itta-tokoro-da": "大约……；也就是（といったところだ）",
    "you-ni-mo-nai": "想……也做不到（ようにもない）",
    "n-ga-tame": "为了……；以期（んがため）",
    "n-bakari": "仿佛要……；眼看（んばかり）",
    "u-ni-mo": "即使想……也（にも）",
    "u-mono-nara": "若敢……；一旦（ものなら）",
    "tari-tomo": "连一个……都不（たりとも）",
    "nashi-ni-without": "没有……就；若无（なしに）",
    "naku-shite-wa": "没有……就；若无（なくしては）",
    "ya-literary": "一……就……（や，书面）",
    "no-kiwami": "……之极；极度（の極み）",
    "te-mae": "顾及……；考虑到（手前）",
    "ni-nottotte": "依照……；根据（に則って）",
    "wo-motte": "以……；用（をもって，郑重）",
    "tokoro-wo": "在……之时；正（ところを）",
    "te-habakaranai": "毫不顾忌……；公然（はばからない）",
    "beku-mo-nai": "无法……；不可能（べくもない）",
    "to-yara": "好像……；据说（とやら）",
    "nai-de-mo-nai": "并非不……；也不是（でもない）",
    "wo-kawakiri-ni": "以……为开端；始于（を皮切りに）",
    "wo-kagiri-ni": "以……为止；终于（を限りに）",
    "ori-ni": "在……之际；当（折に）",
    "nagara-ni": "一边……；依然（ながらに）",
    "oose-ru": "成功做到……；完成（おおせる）",
    "konasu": "熟练处理……；驾驭（こなす）",
    "mekasu": "显出……样子；装（めかす）",
    "ni-hoka-naranai": "无非是……；正是（に他ならない）",
    "mo-saru-koto-nagara": "……自不待言；且（もさることながら）",
    "made-mo-naku": "无须……；不消（までもなく）",
    "nara-mada-shimo": "若是……还罢了（ならまだしも）",
    "nara-iza-shirazu": "若是……另当别论（ならいざ知らず）",
    "hitotabi": "一旦……（ひとたび）",
    "to-shita-tokoro-de": "即使假定……；纵使（としたところで）",
    "hodo-no": "……程度的；如此（ほどの）",
    "zu-mogana": "最好别……；不该（ずもがな）",
    "ni-matsuwaru": "围绕……；有关（にまつわる）",
    "wo-kanete": "兼……；同时（を兼ねて）",
    "de-ari-nagara": "虽是……却（でありながら）",
    "te-mi-se-ru": "一定要……；做给你看（てみせる）",
    "ni-shite-hajimete": "唯有……才；到……才（にして初めて）",
    "nagara-no": "一如……的；原样（ながらの）",
    "ikan-se-n": "无奈……；遗憾的是（いかんせん）",
    "ni-mo-hodo-ga-aru": "……也要有分寸；太（にもほどがある）",
    "ba-sore-made": "若……就完了；到此为止（それまでだ）",
    "mo-nan-tomo-nai": "一点也不……；毫（でもなんともない）",
    "ni-teihyou-ga-aru": "以……著称；有名（に定評がある）",
    "ni-tari-nai": "不值得……；不足（に足りない）",
    "wo-mae-ni-shite": "面对……；面临（を前にして）",
    "tari-mo-shinai": "连……都不做（たりもしない）",
    "ni-ari-gachi": "容易……；往往（にありがち）",
    "sono-mono": "……本身；其物（そのもの）",
    "katagata-combining": "兼……；同时（かたがた）",
    "n-to-suru": "想要……；即将（んとする）",
    "ni-soui-nai": "无疑……；必定（に相違ない）",
    "yue-no": "由于……的；因（ゆえの）",
    "to-atte-wa": "既然是……；当（とあっては）",
    "ni-kakawaru": "关系到……；涉及（に関わる）",
    "mono-wo-if-only": "要是……就好了（ものを）",
    "to-minasu": "视为……；当作（とみなす）",
    "mai-ka-wonder": "会不会……呢；莫非（ではまいか）",
    "hoka-naranu": "正是……；非同小可（ほかならぬ）",
    "ni-aki-tarazu": "不满足于……；犹（に飽き足らず）",
    "beku-shite": "必然……；注定（べくして）",
    "taru-yuen": "成为……的理由；所以（たるゆえん）",
    "iyashiku-mo": "若说……；只要（いやしくも）",
    "n-to-bakari-ni": "仿佛要……；像（んとばかりに）",
    "sanagara": "宛如……；恰似（さながら）",
    "de-atta-to-shitemo": "即使曾是……；纵使（であったとしても）",
    "nomi-only": "只……；仅（のみ，书面）",
    "iwaba": "可谓……；换句话说（いわば）",
    "mo-kamawa-zu": "不顾……；不管（も構わず）",
    "ma-no-atari-ni": "亲眼……；目睹（目の当たりに）",
    "oyoba-zu-nagara": "虽力有不逮；谨（及ばずながら）",
    "naku-te-nan-de-arou": "不是……又是什么（なくてなんであろう）",
    "koto-mo-arou-ni": "偏偏……；竟（こともあろうに）",
    "ni-wa-oyoba-nai": "无须……；比不上（には及ばない）",
    "ni-soku-shite": "按照……；依据（に即して）",
    "to-aimatte": "加上……；与……相辅（と相まって）",
    "tara-kiri-ga-nai": "一旦……就没完；无尽（たらきりがない）",
    "ga-sai-go": "一旦……就不可收拾（が最後）",
    "no-ue-nai": "无比……；绝顶（この上ない）",
    "to-sareru": "被认为……；被视为（とされる）",
    "to-oboshii": "似乎是……；看来（とおぼしい）",
    "wo-hikiai-ni": "以……为例；援引（を引き合いに）",
    "aro-u-koto-ka": "岂有此理……；竟（あろうことか）",
    "koso-are": "虽有……却；尽管（こそあれ）",
    "aro-u-tomo": "无论发生什么；不管（あろうとも）",
    "gurumi": "全……；整个（ぐるみ）",
    "ikkou-ni-nai": "完全不……；丝毫（いっこうに～ない）",
    "ni-nazoraete": "比作……；比拟（になぞらえて）",
    "nuki-de": "不含……；抛开（抜きで）",
    "tou-no": "该……；当事（当の）",
    "wo-kiwameru": "穷尽……；登峰（を極める）",
    "to-wa-urahara-ni": "与……相反；背道（とは裏腹に）",
    "hiite-wa": "进而……；归根结底（ひいては）",
    "yoshi-mi": "看在……份上；为（のよしみで）",
    "nagara-mo": "虽然……却（ながらも）",
    "tada-de-sae": "即便平常……；本来就（ただでさえ）",
    "ashikara-zu": "请勿见怪……；请恕（あしからず）",
    "manzara-de-mo-nai": "并非完全不……；未必（まんざらでもない）",
    "desura": "连……都（ですら，书面）",
    "wo-shirime-ni": "无视……；不顾（を尻目に）",
    "koto-nagara": "一如往常……；照例（ことながら）",
    "to-nareba-if-comes-to": "一旦到了……；若说（となれば）",
    "to-naru-to-when-comes": "一到……就；说起（となると）",
    "majiki-unacceptable": "不该……的；不配（まじき）",
    "gotoku-as-if": "如……般；宛如（ごとく，书面）",
    "gotoki-like": "像……般的；所谓（ごとき）",
    "ni-taru": "值得……；足以（に足る）",
    "ni-taeru": "值得……；堪（に堪える）",
    "ni-taenai": "不忍……；难以（に堪えない）",
    "te-yamanai": "不断……；不禁（てやまない）",
    "wo-kaerimi-zu": "不顾……；不惜（を顧みず）",
    "ni-sakigakete": "领先……；先于（に先駆けて）",
    "to-iedomo": "即使……也；虽（といえども）",
    "to-omoi-kiya": "本以为……却；孰料（と思いきや）",
    "naritomo": "至少……；哪怕（なりとも）",
    "nari-as-soon-as": "一……就……（なり，书面）",
    "nari-ni-in-own-way": "以……特有的；按（なりに）",
    "ga-hayai-ka": "一……就……（が早いか，书面）",
    "ni-kangamite": "鉴于……；鉴于（に鑑みて）",
    "te-shikarubeki": "理应……；自当（しかるべき）",
}

_parser = argparse.ArgumentParser(description=__doc__)
_parser.add_argument(
    "--write",
    action="store_true",
    help="rewrite zh.json from the table below (default: report only)",
)
args = _parser.parse_args()

# ---- read source id union ----
source_ids = []
for lvl in LEVELS:
    with open(os.path.join(BASE, f"{lvl}.json"), encoding="utf-8") as fh:
        for d in json.load(fh):
            source_ids.append(d["id"])

missing = [i for i in source_ids if i not in ZH]
extra = [k for k in ZH if k not in source_ids]

print("source ids:", len(source_ids))
print("zh entries:", len(ZH))
print("missing (in source, not zh):", len(missing))
if missing:
    print("  ", missing[:50])
print("extra (in zh, not source):", len(extra))
if extra:
    print("  ", extra[:50])

# length / emptiness checks
bad = []
for k, v in ZH.items():
    if not v or not (4 <= len(v) <= 40):
        bad.append((k, v, len(v)))
print("value length violations (4~40):", len(bad))
for b in bad[:50]:
    print("  ", b)

if not (missing or extra or bad):
    print("ok: no missing ids, no stale ids, no length violations")

if not args.write:
    print()
    print("(dry run: pass --write to update zh.json)")
    sys.exit(1 if (missing or extra or bad) else 0)

out = os.path.join(BASE, "zh.json")
with open(out, "w", encoding="utf-8") as fh:
    json.dump(ZH, fh, ensure_ascii=False, indent=2)
print("wrote", out)
