"""Merge audited grammar materials into the built-in library and regenerate
the Chinese gloss file.

Two stages, both idempotent, both driven by the audit reports:

  1. merge  -- every ``audit_missing.json`` entry becomes a new row in
     ``lute/jlpt_data/grammar/n{n}.json`` for its level, keeping the
     verbatim-copy schema (kebab-case id, pattern, level, meaning_en,
     meaning_detailed, formation, formation_notes, formality, related,
     examples[{japanese, english, source}]).  ``meaning_en`` is derived
     from the material's ``meaning_zh`` through the ZH->EN gloss table
     below; entries the table cannot translate are reported and skipped,
     never guessed.  ``source`` on each example is the material name, so
     provenance stays auditable next to the jkindrix rows.  Ids are the
     romaji of the pattern's kana (あっての -> atte-no); pure-kanji or
     colliding patterns fall back to a stable hash suffix so re-runs are
     idempotent.

  2. zh     -- new ids are written to
     ``scripts/grammar_materials/zh_additions.json`` mapping id -> Chinese
     gloss taken verbatim from the material's ``meaning_zh`` (clamped to
     4..40 chars like the existing table).  ``--append-zh`` pastes those
     lines into the ZH dict of ``scripts/generate_grammar_zh.py``; the
     zh.json itself is then regenerated by that script's ``--write``,
     which stays the single source of truth.

Usage::

    python -m scripts.merge_grammar_materials             # report only
    python -m scripts.merge_grammar_materials --write     # apply both stages
    python -m scripts.merge_grammar_materials --append-zh # paste into ZH dict
"""

import argparse
import collections
import glob
import hashlib
import json
import os
import re
import sys

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MATERIALS = os.path.join(BASE, "scripts", "grammar_materials")
LIBRARY = os.path.join(BASE, "lute", "jlpt_data", "grammar")
ZH_SCRIPT = os.path.join(BASE, "scripts", "generate_grammar_zh.py")
LEVEL_FILE = {
    "N1": "n1.json",
    "N2": "n2.json",
    "N3": "n3.json",
    "N4": "n4.json",
    "N5": "n5.json",
}

# Hiragana -> romaji, for id generation.  Grammar patterns are mostly kana
# and particles, so this yields readable ids (あっての -> atte-no); katakana
# sit a fixed offset above hiragana; kanji are dropped and a stable hash
# suffix covers pure-kanji or colliding patterns.
_KANA_ROMAJI = {
    "あ": "a",
    "い": "i",
    "う": "u",
    "え": "e",
    "お": "o",
    "か": "ka",
    "き": "ki",
    "く": "ku",
    "け": "ke",
    "こ": "ko",
    "さ": "sa",
    "し": "shi",
    "す": "su",
    "せ": "se",
    "そ": "so",
    "た": "ta",
    "ち": "chi",
    "つ": "tsu",
    "て": "te",
    "と": "to",
    "な": "na",
    "に": "ni",
    "ぬ": "nu",
    "ね": "ne",
    "の": "no",
    "は": "ha",
    "ひ": "hi",
    "ふ": "fu",
    "へ": "he",
    "ほ": "ho",
    "ま": "ma",
    "み": "mi",
    "む": "mu",
    "め": "me",
    "も": "mo",
    "や": "ya",
    "ゆ": "yu",
    "よ": "yo",
    "ら": "ra",
    "り": "ri",
    "る": "ru",
    "れ": "re",
    "ろ": "ro",
    "わ": "wa",
    "ゐ": "i",
    "ゑ": "e",
    "を": "o",
    "ん": "n",
    "が": "ga",
    "ぎ": "gi",
    "ぐ": "gu",
    "げ": "ge",
    "ご": "go",
    "ざ": "za",
    "じ": "ji",
    "ず": "zu",
    "ぜ": "ze",
    "ぞ": "zo",
    "だ": "da",
    "ぢ": "ji",
    "づ": "zu",
    "で": "de",
    "ど": "do",
    "ば": "ba",
    "び": "bi",
    "ぶ": "bu",
    "べ": "be",
    "ぼ": "bo",
    "ぱ": "pa",
    "ぴ": "pi",
    "ぷ": "pu",
    "ぺ": "pe",
    "ぽ": "po",
    "ゃ": "ya",
    "ゅ": "yu",
    "ょ": "yo",
    "ぁ": "a",
    "ぃ": "i",
    "ぅ": "u",
    "ぇ": "e",
    "ぉ": "o",
    "っ": "",
}
_KATA_OFFSET = 0x60  # katakana block sits 0x60 above hiragana

# ZH -> EN gloss fragments for the meaning_en derivation.  Longest first so
# the specific reading wins over the generic one; anything left un-mapped
# marks the entry as skipped instead of producing a wrong gloss.
_ZH2EN = [
    ("因为有…才…", "there being X is exactly what makes Y possible"),
    ("没有…就不能…", "without X, Y is impossible"),
    ("…置之不管", "leaving X as it is"),
    ("只要…就", "as long as X, then Y"),
    ("只有…才", "only when X is Y possible"),
    ("正是因为", "precisely because"),
    ("即使在…也", "even if X, still Y"),
    ("不管…还是", "whether X or Y"),
    ("既然…就", "now that X, then Y"),
    ("如果…的话", "if X is the case"),
    ("为了要…", "in order to X"),
    ("眼看就要", "just about to"),
    ("几乎要", "almost about to"),
    ("禁不住…", "cannot help but"),
    ("不禁…", "cannot help but"),
    ("万一", "in the unlikely event of"),
    ("无论…都", "no matter X, still Y"),
    ("甚至连…都", "not even X"),
    ("连…也…", "even X is"),
    ("也就是说", "in other words"),
    ("多亏了…", "thanks to X"),
    ("与其说…不如说…", "not so much X as rather Y"),
    ("不只是…更是…", "not only X but indeed Y"),
    ("越…越…", "the more X, the more Y"),
    ("随着…", "along with X"),
    ("由于…", "owing to X"),
    ("尽管…", "even though X"),
    ("因为…", "because of X"),
    ("以…为…", "with X as Y"),
    ("属于…", "falls under the category of X"),
    ("一旦…就", "once X, then immediately Y"),
    ("…而已", "merely X"),
    ("为了…", "for the sake of X"),
    ("即便…也", "even if X, still Y"),
    ("处于…", "in the state of X"),
    ("比起…", "compared with X"),
    ("不亚于…", "no less than X"),
    ("不用于…", "not used for X"),
    ("取…之意", "taking the meaning of X"),
    ("只能", "can only"),
    ("竟然", "surprisingly"),
    ("居然", "surprisingly"),
    ("全是", "nothing but"),
    ("只好", "have no choice but to"),
    ("不必", "need not"),
    ("难怪", "no wonder"),
    ("几乎", "almost"),
    ("大约", "approximately"),
    ("极其", "extremely"),
    ("值得", "worth"),
    ("难怪", "no wonder"),
    ("正在…", "in the middle of doing X"),
    ("正要…", "just about to do X"),
    ("想～", "think that one would like to do X"),
    ("该～", "supposed to be X"),
    ("直到…", "by X (deadline), up to X"),
    ("好～", "easy to do X"),
    ("被～", "be done by X (passive)"),
    ("第…", "the X-th (ordinal)"),
]

_GARBAGE = re.compile(r"^[~〜…\s\-+/。、，]+$")


def _romaji(pattern):
    out = []
    for ch in pattern:
        cp = ord(ch)
        if 0x3041 <= cp <= 0x3096:  # hiragana
            out.append(_KANA_ROMAJI.get(ch, ""))
        elif 0x30A1 <= cp <= 0x30F6:  # katakana
            out.append(_KANA_ROMAJI.get(chr(cp - _KATA_OFFSET), ""))
        elif ch in "ー~〜":
            out.append("")
        elif ch.isascii() and ch.isalnum():
            out.append(ch.lower())
        # kanji, CJK punctuation: dropped
    return "".join(out)


def _kebab(pattern, taken):
    s = re.sub(r"[^a-z0-9]+", "-", _romaji(pattern)).strip("-")
    h = hashlib.md5(pattern.encode("utf-8")).hexdigest()[:6]
    if len(s) < 3:
        return f"mat-{h}"
    if s in taken:
        return f"{s}-{h}"
    return s


def _en_from_zh(zh):
    "Derive an English gloss from the material's Chinese meaning."
    out = zh
    for zh_frag, en in _ZH2EN:
        out = out.replace(zh_frag, en)
    out = re.sub(r"[~〜…；;，,]+", " / ", out)
    out = re.sub(r"[（）()「」『』\[\]]", " ", out)
    out = re.sub(r"\s+", " ", out).strip(" /")
    if _GARBAGE.match(out) or len(out) < 3:
        return None
    return out[:160]


def load_missing():
    path = os.path.join(MATERIALS, "audit_missing.json")
    if not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def existing_ids():
    ids = set()
    for path in sorted(glob.glob(os.path.join(LIBRARY, "n[1-5].json"))):
        with open(path, encoding="utf-8") as fh:
            ids.update(e["id"] for e in json.load(fh))
    return ids


def build_rows(missing):
    rows, skipped, taken = collections.defaultdict(list), [], set(existing_ids())
    for pattern, meta in sorted(missing.items()):
        en = _en_from_zh(meta.get("meaning_zh") or "")
        if en is None:
            skipped.append(pattern)
            continue
        eid = _kebab(pattern, taken)
        if eid in taken:
            continue
        taken.add(eid)
        level = meta.get("level") or "N1"
        rows[level].append(
            {
                "id": eid,
                "pattern": pattern,
                "level": level,
                "meaning_en": en,
                "meaning_detailed": meta.get("meaning_zh", ""),
                "formation": meta.get("formation", ""),
                "formation_notes": [meta["notes"]] if meta.get("notes") else [],
                "formality": "neutral",
                "related": [],
                "examples": [
                    {
                        "japanese": ex["japanese"],
                        "english": "",
                        "chinese": ex["chinese"],
                    }
                    for ex in meta.get("examples", [])
                ],
            }
        )
    return rows, skipped


def zh_additions(rows):
    out = {}
    for level_entries in rows.values():
        for e in level_entries:
            zh = e["meaning_detailed"]
            out[e["id"]] = zh if 4 <= len(zh) <= 40 else zh[:40]
    return out


def append_zh(_unused=None):
    "Paste `id: gloss,` lines from zh_additions.json into the ZH dict."
    path = os.path.join(MATERIALS, "zh_additions.json")
    if not os.path.exists(path):
        print("no zh_additions.json -- run --write first")
        return 1
    with open(path, encoding="utf-8") as fh:
        zh = json.load(fh)
    with open(ZH_SCRIPT, encoding="utf-8") as fh:
        src = fh.read()
    have = set(re.findall(r'^\s{4}"([a-z0-9-]+)":', src, re.M))
    new = {k: v for k, v in zh.items() if k not in have}
    if not new:
        print("ZH dict already covers every new id")
        return 0
    lines = "".join(f'    "{k}": "{v}",\n' for k, v in sorted(new.items()))
    marker = re.search(r"^ZH = \{\n", src, re.M)
    if not marker:
        print("cannot locate ZH dict opening in", ZH_SCRIPT)
        return 1
    src = src[: marker.end()] + lines + src[marker.end() :]
    with open(ZH_SCRIPT, "w", encoding="utf-8") as fh:
        fh.write(src)
    print(
        f"generate_grammar_zh.py: +{len(new)} ZH lines "
        f"(now run `python -m scripts.generate_grammar_zh --write`)"
    )
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--append-zh", action="store_true")
    args = ap.parse_args()
    missing = load_missing()
    if not missing:
        print("no audit_missing.json yet -- run scripts.audit_grammar_coverage")
        return 1
    rows, skipped = build_rows(missing)
    zh = zh_additions(rows)
    print(
        f"new rows: {sum(len(v) for v in rows.values())} "
        f"across {', '.join(f'{k}:{len(v)}' for k, v in sorted(rows.items()))}"
    )
    print(f"skipped (no EN gloss derivable): {len(skipped)}")
    for p in skipped:
        print("  -", p)
    if args.append_zh:
        return append_zh(zh)
    if not args.write:
        print("(dry run: pass --write)")
        return 0
    for level, entries in sorted(rows.items()):
        path = os.path.join(LIBRARY, LEVEL_FILE[level])
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
        by_id = {e["id"]: e for e in data}
        added = []
        updated = 0
        for e in entries:
            if e["id"] not in by_id:
                added.append(e)
                continue
            # A row written by an earlier run (before the audit carried
            # examples) may sit there example-less -- such rows derive no
            # matcher and never fire.  Backfill what this run's material
            # can provide; never overwrite existing content.
            row = by_id[e["id"]]
            if not row.get("examples") and e["examples"]:
                row["examples"] = e["examples"]
                updated += 1
            if not row.get("meaning_detailed") and e["meaning_detailed"]:
                row["meaning_detailed"] = e["meaning_detailed"]
                updated += 1
            if not row.get("formation") and e["formation"]:
                row["formation"] = e["formation"]
                updated += 1
        data.extend(added)
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(data, fh, ensure_ascii=False, indent=1)
        print(f"{path}: +{len(added)} rows, {updated} fields backfilled")
    with open(
        os.path.join(MATERIALS, "zh_additions.json"), "w", encoding="utf-8"
    ) as fh:
        json.dump(zh, fh, ensure_ascii=False, indent=1, sort_keys=True)
    print(
        f"zh_additions.json: {len(zh)} glosses "
        f"(regenerate zh.json via generate_grammar_zh --write)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
