"""The Chinese wording shipped for the 595 vendored jkindrix rows.

``lute/jlpt_data/grammar/zh_enrichment.json`` is what the reading-page
grammar panel shows for those rows in a Chinese panel -- their English
接续 / 注意点 / 例句译文.  It is generated by ``scripts.enrich_grammar_zh``
from two inputs: the translations, and the Chinese study materials where
they cover the same grammar point.  These tests pin the file to the
generator and to the provenance it records, so a hand edit or a stale
re-run cannot quietly put the wrong Chinese (or English) on the panel.
"""

import json
import os
import re
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_BASE = os.path.abspath(os.path.join(_HERE, "..", ".."))
if _BASE not in sys.path:
    sys.path.insert(0, _BASE)

from scripts import enrich_grammar_zh as enrich  # noqa: E402

_LATIN_WORD = re.compile(r"[A-Za-z]{3,}")


def _load(path):
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def test_the_shipped_file_is_what_the_generator_produces():
    """
    Re-deriving must reproduce the file exactly: the sources are the
    materials plus the translations, so any hand edit shows up here.
    """
    base = _load(enrich.ENRICHMENT)
    derived, derived_sources = enrich.build(
        base, enrich.load_library(), enrich.load_materials()
    )
    assert derived == base
    assert derived_sources == _load(enrich.SOURCES)


def test_provenance_names_real_materials():
    "Every non-translated field points at a material file that exists."
    materials = {name for name, _ in enrich.load_materials()}
    for entry_id, source in _load(enrich.SOURCES).items():
        for field, origin in source.items():
            assert (
                origin == "translated" or origin in materials
            ), f"{entry_id} {field}: unknown source {origin!r}"


def test_material_sourced_text_is_verbatim_from_that_material():
    """
    A field credited to a material must carry that material's own words --
    modulo the OCR repair the generator applies ('?' for a lost '/').
    """
    enrichment = _load(enrich.ENRICHMENT)
    by_file = {}
    for (name, _), entries in enrich.load_materials().items():
        for entry in entries:
            by_file.setdefault(name, []).append(entry)

    def repair(text):
        return enrich._OCR_SLASH.sub("/", (text or "").strip())

    for entry_id, source in _load(enrich.SOURCES).items():
        for field in ("formation", "notes"):
            origin = source[field]
            if origin == "translated":
                continue
            value = repair(enrichment[entry_id].get(field))
            found = {repair(e.get(field)) for e in by_file[origin]}
            assert value in found, f"{entry_id} {field} is not from {origin}"


def test_no_english_reaches_a_chinese_panel():
    "The whole point of the file: no English word in anything it supplies."
    for entry_id, row in _load(enrich.ENRICHMENT).items():
        values = [row.get("formation") or "", row.get("notes") or ""]
        values += list((row.get("examples") or {}).values())
        for value in values:
            hit = _LATIN_WORD.search(value)
            assert not hit, f"{entry_id}: English {hit.group()!r} in {value!r}"


def test_every_row_carries_the_three_panel_fields():
    "The panel renders 接续, 注意点 and the reference translation."
    for entry_id, row in _load(enrich.ENRICHMENT).items():
        assert (row.get("formation") or "").strip(), entry_id
        assert (row.get("notes") or "").strip(), entry_id
        assert row.get("examples"), entry_id
